#include<stdio.h>
#include<iostream>

using namespace std;

int main(){
	
	cout <<"IF-ELSE-NESTED Condition.....!\n";
	printf("\n");
	
	
	//driving license rule : 18 + can apply for license 
	
	int age;
	
	printf("Checking your age for DL Apply ....\n");
	printf("Enter your age >>: \n");
	cin>>age;


if(age>=18){
	
	printf("Hey Congrats ..! \n You're Fall under 18+ categories for DL' \n");
	
	if(age>=18){
		
		printf("\n You're Eligible to Apply for DL' \n");
	
	
	
	
}}

else{
	
	printf("NO.....! \n You're  NOT  Eligible to Apply for DL' \n");
}
	
	
	
	
	

	
}
