#include <iostream>
using namespace std;

// ONE MORE WAY TO INITIALIZE STRUCTURE MEMBERS CALLED=> DEESIGNATED INITIALIZATION

struct Student

{
    int roll_no;
    string name;
    string address;
};

int main()
{

    //    support in C  //struct Student S = {.address="Chandigarh",.name="LAKSH",.roll_no=90}; // here suene is not important becos we are using  membership

    return 0;
}